#%RAML 1.0 NamedExample

values:
  -
    ID : 1
    firstName : gnana
    lastName : palaniyappan
    address : Indhara nagara
    postal : 636003
    country : india
    miles : 123
    creationDate : 2017/07/26
    type : business
  -
    ID : 2
    firstName : gnana
    lastName : palaniyappan
    address : Indhara nagara
    postal : 636003
    country : india
    miles : 123
    creationDate : 2017/07/26
    type : business
   